# Generated by Django 5.2.14 on 2026-05-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='heartbeatmetric',
            new_name='fleet_heart_device__d2b4db_idx',
            old_name='fleet_heart_device__b8e0f0_idx',
        ),
    ]
